
language: java
jdk:
  - openjdk13

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="d293131a-914f-4e2b-8483-ce2a4f3f4619"

notifications:
  email:
    recipients:
      -zaharenkoiv93@gmail.com
    on_success: never # default: change
    on_failure: always # default: always